# Generated by Django 4.0.5 on 2022-07-31 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favicon_zip',
            name='html_code',
        ),
        migrations.AlterField(
            model_name='favicon_zip',
            name='image_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.image'),
        ),
    ]
