# Generated by Django 4.0.6 on 2022-07-27 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('user_account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_account_email_address', models.EmailField(max_length=255, unique=True)),
                ('user_account_password', models.CharField(max_length=255)),
                ('user_account_phone_number', models.CharField(max_length=10, unique=True)),
                ('user_account_security_question', models.CharField(max_length=255)),
                ('user_account_security_answer', models.CharField(max_length=255)),
                ('user_account_image_url', models.CharField(max_length=255)),
                ('user_account_color', models.CharField(default='ffffff', max_length=6)),
                ('user_account_theme', models.BinaryField(default=0)),
                ('user_account_is_active', models.BinaryField(default=1)),
                ('user_account_creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-user_account_creation_date',),
            },
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('image_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=255)),
                ('image_file_type', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('image_upload_date', models.DateTimeField(auto_now_add=True)),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user_account')),
            ],
            options={
                'ordering': ('-image_upload_date',),
            },
        ),
        migrations.CreateModel(
            name='favicon',
            fields=[
                ('favicon_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('favicon_name', models.CharField(max_length=255)),
                ('favicon_path', models.CharField(max_length=255)),
                ('favicon_creation_date', models.DateTimeField(auto_now_add=True)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.image')),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user_account')),
            ],
            options={
                'ordering': ('-favicon_creation_date',),
            },
        ),
    ]
