# Generated by Django 4.0.6 on 2022-07-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_image_docfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='docfile',
            new_name='media',
        ),
    ]
