# Generated by Django 4.0.6 on 2022-07-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_docfile_image_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
